name: trustedtallentsvalley
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0

  # Fixed Firebase versions known to work together on web
  firebase_core:
  firebase_auth: ^5.5.3
  cloud_firestore:

  # Alternative to firebase_analytics for web
  firebase_analytics:

  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.2.1
  flutter_screenutil: ^5.8.4  # Added specific version
  shared_preferences: ^2.1.1  # Added specific version
  easy_localization: ^3.0.0-nullsafety
  syncfusion_flutter_charts: ^29.2.4  # Updated version

  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.4
  url_launcher: ^6.2.4
  rename: ^3.0.2
  go_router: ^14.2.7
  flutter_expandable_table: ^2.1.0
  flutter_dotenv: ^5.1.0
#  go_provider: ^0.2.2  # Added specific version
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#dependency_overrides:
#  firebase_core_web: 2.10.0
  #  firebase_storage: ^12.3.7
#  cloud_firestore: ^5.6.0
# Use precise version overrides to ensure compatibility
#dependency_overrides:
#  firebase_core_web: ^2.5.0
#  firebase_auth_web: ^5.5.2  # Changed to 5.5.2 which is more compatible
#  firebase_analytics_web: ^0.5.4+2
#  cloud_firestore_web: ^3.6.0

flutter:
  uses-material-design: true
  # Uncomment these lines if you have these assets
  # assets:
  #   - assets/translations/
  #   - assets/.env